swagger: "2.0"
info:
  version: 1.0.0
  title: WEMOOC API
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: DAVID NEVADO
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: miriadaxdes.miriadax.net
basePath:/api/jsonws
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/jsonws/assetcategory
    get:
      description: |
        CATEGORY ID
      operationId: /get-category
      parameters:
      - name: categoryId
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: pet response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
